### ISSUE TITLE
TypeError: create_curvilinear_collision_checker(): incompatible function arguments. 

### ISSUE THREAD

**Issue by Yangli0505** [CommonRoad/commonroad-reachable-set#5]
I am running "compute_reachable_set.py", but I got the following errors:

TypeError: create_curvilinear_collision_checker(): incompatible function arguments. The following argument types are supported:
    1. (arg0: List[List[numpy.ndarray[numpy.float64[2, 1]]]], arg1: Dict[int, List[List[numpy.ndarray[numpy.float64[2, 1]]]]], arg2: geometry::CurvilinearCoordinateSystem, arg3: float, arg4: int, arg5: bool, arg6: bool) -> collision::CollisionChecker
    
    
It seems that the function "create_curvilinear_collision_checker()" got the wrong function arguments. But I do not know how to fix this.

**Comment by Lerbert** [comment]
Hey, which `numpy` version are you using? It is a known problem that the package only works with `numpy<2.0`.

**Comment by Yangli0505** [comment]
I have numpy == 1.26.4. I guess it is not caused by the numpy version. 
I use the combination of following packages, this problem has gone as well, like the last issue. Therefore, the problem might come from the mismatch between the following packages. Now, all codes are running correctly with the following combination:  
 
commonroad-drivability-checker 2023.1
commonroad-io                  2024.2
commonroad-reach               2024.1.2
commonroad-route-planner       2024.2.0

By the way, first build "commonroad-drivability-checker", then build "commonroad-reachable-set", last just "pip install commonroad-route-planner==2024.2.0".  

Finally, all works! Thanks for you help!
