### ISSUE TITLE
AttributeError: 'list' object has no attribute 'retrieve_first_route'

### ISSUE THREAD

**Issue by Yangli0505** [CommonRoad/commonroad-reachable-set#6]
I am running the tutorials and I got the following errors:

AttributeError: 'list' object has no attribute 'retrieve_first_route', in 
route = candidate_holder.retrieve_first_route().

It comes from the config.update(). In configuration.py, the self.planning.update_configuration(self).

**Comment by Lerbert** [comment]
Which version of `commonroad-route-planner` are you using? If it is `2025.X.Y`, please try with one of the `2024.X.Y` (e.g., `2024.2.0`) versions, as we have not yet updated the package for the new route planner versions.

**Comment by Yangli0505** [comment]
pip install commonroad-route-planner==2024.2.0, yes, I just solved it! Thanks!
By the way,  it works with the commonroad-drivablity-checker==2023.1。

The following version work with the codes:

commonroad-drivability-checker 2023.1
commonroad-io                  2024.2
commonroad-reach               2024.1.2
commonroad-route-planner       2024.2.0
commonroad-vehicle-models      3.0.2
